import type { Metadata } from 'next'
import { Copse, Nunito, Varela } from 'next/font/google'
import './globals.css'

const varela = Varela({
  variable: '--font-varela',
  subsets: ['latin'],
  weight: ['400'],
})

const copse = Copse({
  variable: '--font-copse',
  subsets: ['latin'],
  weight: ['400'],
})

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900', '1000'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fr">
      <body
        className={`${varela.variable} ${copse.variable} ${nunito.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
