import type { Metadata } from 'next'
import { Copse, Nunito, Varela } from 'next/font/google'
import './globals.css'
import Head from 'next/head'
import { serviceGetLoggedInUser } from '@/shared/services/user'
import UserProvider from '@/shared/components/providers/UserProvider'

const varela = Varela({
  variable: '--font-varela',
  subsets: ['latin'],
  weight: ['400'],
})

const copse = Copse({
  variable: '--font-copse',
  subsets: ['latin'],
  weight: ['400'],
})

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900', '1000'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const user = await serviceGetLoggedInUser()

  return (
    <html lang="fr">
      <Head>
        <link
          rel="preload"
          as="image"
          href="/images/bg/app-bg.png"
        />
      </Head>
      <body
        className={`${varela.variable} ${copse.variable} ${nunito.variable} antialiased font-nunito bg-global-background relative app-bg`}
      >
        <UserProvider user={user}>{children}</UserProvider>
      </body>
    </html>
  )
}
